const RouteName = {
    SPLSH_SCREEN: "SplashScreen",
    GET_STARTED_SLIDER_SCREEN: "GetstartedSliderscreen",
    ABOUT_SELF_SCREEN: "AboutSelfScreen",
    AGE_SCREEN: "AgeScreen",
    TRLANSTION_SCREEN: "TranslationScreen",
    WEIGHT_SCREEN: "WeightScreen",
    GOAL_SCREEN: "GoalScreen",
    WE_HELP_SCREEN: "WeHelpScreen",
    LOGIN_SCREEN: "LoginScreen",
    SIGNUP_SCREEN: "SignUpScreen",
    OTP_VERYFY_SCREEN: "OtpVerifyScreen",
    HOME_SCREEN: "HomeScreen",
    WORKOUT_DETAIL_SCREEN: "WorkoutDetailScreen",
    READY_TO_GO_SCREEN: "ReadyToGoScreen",
    START_SCREEN: "StartScreen",   
    TAKE_REST_SCREEN: "TakeRestScreen",   
    EXERCISE_VIDEO_SCREEN: "ExerciseVideo",   
    REPORT_SCREEN: "ReportScreen",   
    STEP_COUNTER_SCREEN: "StepCounterScreen",   
    EDIT_PROFILE_SCREEN: "EditProfileScreen",   
    APP_SETTINGS_SCREEN: "AppSettingsScreen",   
    HELP_SCREEN: "HelpScreen",   
    YOGA_SCREEN: "YogaScreen",   
    CATEGORY_SCREEN: "CategoryScreen",   
    MEDITATION_SCREEN: "MeditationScreen",   
    FORGOT_PASSWORD_SCREEN: "ForgotPasswordScreen",   
}
export default RouteName;