export const USERREGISTER_TYPE = 'USERREGISTER_TYPE';
export const OTP_SEND_TYPE = 'OTP_SEND_TYPE';
export const LOG_OUT = 'LOG_OUT';
export const AUTH_RESET_INITIAL_STATE = 'AUTH_RESET_INITIAL_STATE';
export const USERLOGIN_TYPE = 'USERLOGIN_TYPE';